### PR TITLE
issue #111

### PR DESCRIPTION
**Pull request by kaushik853**
deprecation of CodeQL Action v1, changed to v2

### CODE REVIEW

**Review by haya-ahmed — APPROVED** [review]
Looks good according to: [](https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/)

**Comment by kaushik853** [comment]
I am not sure why the terraform validation fails?

**Comment by kaushik853** [comment]
@jdyke @haya-ahmed  can you guys help

**Comment by jdyke** [comment]
> @jdyke @haya-ahmed  can you guys help

Looks like we need to remove one forward slash:

`InvalidUrlError: Cloud URL scheme should be followed by colon and two slashes: "://". Found: "gs:///terraform.tfvars". `

**Comment by kaushik853** [comment]
@jdyke Hi Jason are you talking about tf.yml file and these lines "gsutil cp gs://${{ secrets.GCP_TFVAR_BUCKET_PROD }}/terraform.tfvars ./terraform.tfvars"

**Comment by jdyke** [comment]
> @jdyke Hi Jason are you talking about tf.yml file and these lines "gsutil cp gs://${{ secrets.GCP_TFVAR_BUCKET_PROD }}/terraform.tfvars ./terraform.tfvars" 

It can't find the bucket name and instead it's grabbing the vars file and using it as the bucket name. 

The 3 forward slashes were correct because the "/terraform.tfvars" is actually used to separate the bucket name and the file name. 

I can't see the variables on my phone and why it's empty. @haya-ahmed can you take a look?

**Comment by jdyke** [comment]
`secrets.GCP_TFVAR_BUCKET_PROD` is the secret it cannot find. @aaronrea @haya-ahmed

**Review by JackAtScaleSec — APPROVED** [review]

**Comment by JackAtScaleSec** [comment]
Closing this PR, https://github.com/ScaleSec/gcp_org_policy_notifier/pull/132 with the same changes, but from a non-forked source branch was merged in. 

(This was done due to GitHub not pulling secrets when a build is 'triggered from a forked repository'. https://docs.github.com/en/actions/security-guides/encrypted-secrets)

**Pull request closed without merging**
